### ISSUE TITLE
Wild Zoea Round 2 (-80F) Freezer Space Question

### ISSUE THREAD

**Issue by KROVINSKI** [NWFSC-OA-lab/dng_zoe_exo_skl_2021#13]
- [x] Request freezer space from Eric Iwamoto at eric.iwamoto@noaa.gov

**Comment by pmcelhany** [comment]
The molts cna just go into the -80 without liquid nitrogen. Since they are already dead, no need to flash freeze

**Comment by pmcelhany** [comment]
@KROVINSKI good that you created an issue for this - you win prize for the first issue in NWFSC-OA-lab not created by me!

**Comment by pmcelhany** [comment]
You can drag this issue onto the exoskelton project board.
