### ISSUE TITLE
Data transfer / Generation from raw data care sheet

### ISSUE THREAD

**Issue by KROVINSKI** [NWFSC-OA-lab/dng_zoe_exo_skl_2021#15]
Create R friendly data from raw data care sheet google document ([https://docs.google.com/spreadsheets/d/1NVwGLl_vePWsfGzbsV1b7ATxFu-Fc_m7mTXaBFqxNW8/edit?usp=sharing](url)

**Comment by pmcelhany** [comment]
combined with another issue
