### ISSUE TITLE
Paul Review/CHOP on Cornet Bay MEG SOP (exSKEL take#2)

### ISSUE THREAD

**Issue by KROVINSKI** [NWFSC-OA-lab/dng_zoe_exo_skl_2021#16]
Paul Review/CHOP on collection SOP for Cornet Bay "Wild" Meg [SOP](https://docs.google.com/document/d/18tz3fVXo_TmOf8kGA2bXGaEfJR6yYmC6BbEDc5-7yac/edit?usp=sharing) @pmcelhany

**Comment by pmcelhany** [comment]
combined this note with another issue
