### ISSUE TITLE
Calcium spike

### ISSUE THREAD

**Issue by pmcelhany** [NWFSC-OA-lab/dng_zoe_exo_skl_2021#29]
The google drive purchasing folder is [here](https://drive.google.com/drive/folders/1TjXAu4XsDQZlbLp4pJ4NwYweTUfGknZb?usp=sharing).
- [x] list what we have
- [x] look at source (look at kathleen vendor list)
- [x] Get new quotes
- [x] If Ca-48 is not available, make a new purchase plan
- [x] Switch to Ca-42?
- [x] Order Ca-42
- [ ] Receive Ca-42
- [ ] We bought 114 mge of 83% Ca-42

**Comment by pmcelhany** [comment]
@CoralMaker  We have 10 mge of Ca-43 and 15 mge of Ca-44. [Here](https://drive.google.com/file/d/1NuppC1PG2t37wGNORaSXK7epAuR0frMj/view?usp=sharing) is the invoice. Back in 2020, we also got [three quotes](https://docs.google.com/spreadsheets/d/1Dx87UF0GQKIkaUXPu01nGdEdIzUveUNX/edit?usp=sharing&ouid=111762220101266646499&rtpof=true&sd=true) for isotopes. Not sure what the pandemic has done to isotope supply chains or costs. Also, when we started, I made an [R notebook](https://github.com/NWFSC-OA-lab/ca_isotopes/tree/main/R) based on info you sent me to calculate how much isotope we would need. [Here](https://github.com/NWFSC-OA-lab/ca_isotopes/blob/main/R/CaIsotope.docx) is the notebook rendered as a  Word doc to download, which is a little easier to read. How much and which isotopes do you recommend we get now? We have a $3,500 credit card limit.

**Comment by pmcelhany** [comment]
@CoralMaker It would be great to put in an order for $3.5k of isotopes, just so we have some more on hand as we start experiments. What would your recommend we get? I could just copy our last order, but maybe we want some of a different isotope too so we can try the double spike. Maybe we can finalize this tomorrow?
-paul

**Comment by CoralMaker** [comment]
Good plan.
-Alex

**Comment by pmcelhany** [comment]
also look at oak ridge https://www.isotopes.gov/catalog

**Comment by pmcelhany** [comment]
bought isotopes
