### ISSUE TITLE
Set up crab cleaning at Montlake

### ISSUE THREAD

**Issue by pmcelhany** [NWFSC-OA-lab/dng_zoe_exo_skl_2021#31]
- [x] get shaker table
- [ ] set up aspirator
- [ ] set up chemicals
- [x] acquire tubes (which tubes do we need? 15 ml falcon and 2.5 ml micro?)
- [ ] Buy silica gel desicator
- [ ] Get container for dessicator

**Comment by pmcelhany** [comment]
tubes
https://www.fishersci.com/shop/products/nunc-15ml-50ml-conical-sterile-polypropylene-centrifuge-tubes/p-4526024#?keyword=

**Comment by dmperez89** [comment]
@pmcelhany you could double check with Alex, but because our crab bits are so small, I don't think we'd need the 15 mL tubes. So maybe just the 2.5 mL tubes, which we might have. I'll try to find the original supply list and compare it with what we've got in the lab.

**Comment by pmcelhany** [comment]
sounds good. please let me know if we need more of the 2.5

**Comment by pmcelhany** [comment]
set up complete
