### ISSUE TITLE
Calcium spike solution

### ISSUE THREAD

**Issue by pmcelhany** [NWFSC-OA-lab/dng_zoe_exo_skl_2021#38]
The calcium spike solution document is [here](https://docs.google.com/document/d/1CBCoAb2VdX8GFS7ajDHua125in19SFRoEFwApLPvseQ/edit?usp=sharing).
The document is and edited version of a knitted R notebook in [this repo](https://github.com/NWFSC-OA-lab/ca_isotopes).

Make spike solutions

- [x] practice weight method of measuring liquid
- [x] make 500 ml of HCl solution at correct normality
- [x] make 5 ml of enriched spike solution (ca43 with 3x enrichment)
- [x] make 100 ml of natural spike solution (same total Ca concentration as enriched spike)

**Comment by pmcelhany** [comment]
@dmperez89 Is this done?

**Comment by dmperez89** [comment]
@pmcelhany Yup!
