### ISSUE TITLE
Crab hatch status 

### ISSUE THREAD

**Issue by pmcelhany** [NWFSC-OA-lab/dng_zoe_exo_skl_2021#43]
Link to table of crab status

**Comment by pmcelhany** [comment]
@michaelmaher114 @dmperez89 
Can you make a quick csv table of crab hatching status with estimated hatch timing and link to this issue?

**Comment by michaelmaher114** [comment]
Here is the estimated crab hatching table from 2/17/2022

[Crab Hatching Table](https://drive.google.com/file/d/19ezPO9UrjaOZ07sATqihnCz_IdiZQMg9/view?usp=sharing)

**Comment by michaelmaher114** [comment]
I made a quick table and uploaded it.

Mike

**Comment by pmcelhany** [comment]
@michaelmaher114 Can you do a quick update of the hatch table? thanks

**Comment by pmcelhany** [comment]
only one crab left
