### ISSUE TITLE
Water and zoea samples to alex

### ISSUE THREAD

**Issue by pmcelhany** [NWFSC-OA-lab/dng_zoe_exo_skl_2021#57]

**Comment by pmcelhany** [comment]
- [ ] Prepare sample metadata sheet
- [ ] Deliver samples to Alex

**Comment by pmcelhany** [comment]
@dmperez89 @KROVINSKI @michaelmaher114 
I'm going to take the frozen water samples to Alex tomorrow. Can you please show me where they are (I'm at Montlake today). I want to take them over on dry ice or liquid nitrogen. Do we have acess to the N2 and a dewar or should I pickup dry ice at QFC on my way in tomorrow?

**Comment by KROVINSKI** [comment]
@pmcelhany we borrowed the dewar from Krista last year and prior

**Comment by michaelmaher114** [comment]
We would also need to check if there is any liquid N2 in the tank - second
floor side room by the lockers and the loading dock.

**Comment by pmcelhany** [comment]
@dmperez89 @KROVINSKI 
I added [metadata to the exoskeleton experiment water samples file.](https://github.com/NWFSC-OA-lab/dng_zoe_exo_skl_2022/blob/main/data_raw/water_zoea_samples/water_for_ca_samples_2022_withMeta.csv). Can you please take a look to see if what I added is right? Best approach is to clone the repo, make edits to the file then push it back to github. You should coordinate to only work on it one at a time so we don't get merge conflicts. Let me know in comments on this issue how it goes with the review of the metadata.

**Comment by dmperez89** [comment]
@pmcelhany the metadata looks pretty good to me. all I did was change Kate's name to Mike's since Kate was still on leave during the 2022 crab experiment. It also looks like we used chamber 3, so I added "ch03" to the chamber row, edited the "variable_min" and added it to the "label" description. 
I pushed everything so you should be able to see those changes.

**Comment by pmcelhany** [comment]
Moved water samples to alex at UW
