### ISSUE TITLE
Micro-dissection parts

### ISSUE THREAD

**Issue by dmperez89** [NWFSC-OA-lab/dng_zoe_exo_skl_2021#7]
- [ ] [Micro-injection plates](https://www.adaptivesciencetools.com/microinjection-molds-for-zebrafish-and-xenopus1.html)
- [ ] [Fine forceps](https://www.finescience.com/en-US/Products/Forceps-Hemostats/Fine-Forceps)

**Comment by pmcelhany** [comment]
Combine with another issue
