### ISSUE TITLE
Wild zoea rearing round 1: 09 June 2021

### ISSUE THREAD

**Issue by pmcelhany** [NWFSC-OA-lab/dng_zoe_exo_skl_2021#9]
- [x] 1. Create data sheet 
- [x] 2. Collect zoea from swimonish
- [x] 3. Transport to Montlke (coolers, icepack bubbler)
- [x] 4. Rough count of zoea - decide how to partition (if few zoea - then all in EtOH)
- [x] 5. Preserve ~half (depending on how many) of zoea in EtOH (need EtOH, jar/tube) Separate by rough morphology
- [x] 6. Sort zoea in 6 well plates (3 per plate) separate out by rough morphology
- [x] 7. Record description of zoea in well
- [ ] 8. Take picture of zoea in each well (optional if not enough time)
- [x] 9. Feed Artemia/ water change (twice per week e.g. Tues/Friday or Mon/Friday)
- [x] 10. Check for molts three days/week (M/W/F)
- [x] 11. Preserve molts in EtOH - separate jars by morphological group
- [x] 12. Max rearing is ~2 weeks

**Comment by pmcelhany** [comment]
@dmperez89 Can you please add zoea collection date  the title of this issue? We will collect multiple rounds of zoea, each with their own issue and I want to keep them straight

**Comment by dmperez89** [comment]
@pmcelhany Just confirming that if a crab molts but I can't tell which crab it was, that I should preserve the molt, but leave all crabs in the wells? This is the first time it's not been obvious (going from one zoea stage to another as opposed to zoea to mega).

**Comment by pmcelhany** [comment]
Yes. Leave it in the well since we don't know who it is.

**Comment by dmperez89** [comment]
All remaining crabs preserved in ethanol on 6/23/2021. No photographs were taken since I could never get the camera to work, but otherwise I think it went well. I'll close this issue out.
